using System.Diagnostics;
using System.IO;
using System.Text;

namespace BhavaniSupportSuite.Services;

public class RemoteConnection
{
    public string Name { get; set; } = string.Empty;
    public string Host { get; set; } = string.Empty;
    public int Port { get; set; }
    public string Protocol { get; set; } = string.Empty;
    public string Username { get; set; } = string.Empty;
    public DateTime LastUsed { get; set; }
}

public class ReportsService
{
    public static async Task LaunchRdpAsync(string host, int port = 3389, string username = "")
    {
        var args = $"/v:{host}:{port}";
        if (!string.IsNullOrEmpty(username))
            args += $" /u:{username}";

        var process = new Process
        {
            StartInfo = new ProcessStartInfo
            {
                FileName = "mstsc.exe",
                Arguments = args,
                UseShellExecute = true
            }
        };
        process.Start();
        await Task.CompletedTask;
    }

    public static async Task LaunchSshAsync(string host, int port = 22, string username = "")
    {
        var user = string.IsNullOrEmpty(username) ? Environment.UserName : username;
        var process = new Process
        {
            StartInfo = new ProcessStartInfo
            {
                FileName = "cmd.exe",
                Arguments = $"/c start cmd /k ssh {user}@{host} -p {port}",
                UseShellExecute = false,
                CreateNoWindow = false
            }
        };
        process.Start();
        await Task.CompletedTask;
    }

    public static async Task LaunchVncAsync(string host, int port = 5900)
    {
        var possiblePaths = new[]
        {
            @"C:\Program Files\RealVNC\VNC Viewer\vncviewer.exe",
            @"C:\Program Files (x86)\RealVNC\VNC Viewer\vncviewer.exe",
            @"C:\Program Files\TightVNC\tvnviewer.exe",
            @"C:\Program Files (x86)\TightVNC\tvnviewer.exe"
        };

        var vncPath = possiblePaths.FirstOrDefault(File.Exists);
        if (vncPath != null)
        {
            var process = new Process
            {
                StartInfo = new ProcessStartInfo
                {
                    FileName = vncPath,
                    Arguments = $"{host}:{port}",
                    UseShellExecute = true
                }
            };
            process.Start();
        }
        else
        {
            var process = new Process
            {
                StartInfo = new ProcessStartInfo
                {
                    FileName = "cmd.exe",
                    Arguments = $"/c start cmd /k echo VNC Viewer not found. Install RealVNC or TightVNC.",
                    UseShellExecute = false
                }
            };
            process.Start();
        }
        await Task.CompletedTask;
    }

    public static async Task<string> GenerateHtmlReportAsync(string hostname, Dictionary<string, string> systemData)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<!DOCTYPE html>");
        sb.AppendLine("<html><head><title>Bhavani Technology - Diagnostic Report</title>");
        sb.AppendLine("<style>");
        sb.AppendLine("body { font-family: 'Segoe UI', sans-serif; background: #181824; color: #E0E0E0; margin: 40px; }");
        sb.AppendLine(".header { text-align: center; border-bottom: 3px solid #00ADB5; padding-bottom: 20px; margin-bottom: 30px; }");
        sb.AppendLine(".header h1 { color: #00ADB5; font-size: 28px; margin: 0; }");
        sb.AppendLine(".header p { color: #888; margin: 5px 0 0 0; }");
        sb.AppendLine(".card { background: #222232; border-radius: 12px; padding: 20px; margin: 15px 0; box-shadow: 0 4px 6px rgba(0,0,0,0.3); }");
        sb.AppendLine(".card h2 { color: #00ADB5; margin: 0 0 15px 0; font-size: 18px; }");
        sb.AppendLine(".info-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #2A2A3C; }");
        sb.AppendLine(".info-label { color: #888; }");
        sb.AppendLine(".info-value { color: #E0E0E0; font-weight: bold; }");
        sb.AppendLine(".footer { text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #2A2A3C; color: #666; font-size: 12px; }");
        sb.AppendLine("</style></head><body>");

        sb.AppendLine("<div class='header'>");
        sb.AppendLine("<h1>Bhavani Support Suite Pro</h1>");
        sb.AppendLine("<p>Diagnostic Report - Generated by Lead Engineer: Dharmesh Varia</p>");
        sb.AppendLine($"<p>Bhavani Technology | {DateTime.Now:yyyy-MM-dd HH:mm:ss}</p>");
        sb.AppendLine("</div>");

        sb.AppendLine("<div class='card'><h2>System Information</h2>");
        foreach (var kvp in systemData)
        {
            sb.AppendLine($"<div class='info-row'><span class='info-label'>{kvp.Key}:</span><span class='info-value'>{kvp.Value}</span></div>");
        }
        sb.AppendLine("</div>");

        sb.AppendLine("<div class='card'><h2>Report Details</h2>");
        sb.AppendLine($"<div class='info-row'><span class='info-label'>Generated:</span><span class='info-value'>{DateTime.Now:yyyy-MM-dd HH:mm:ss}</span></div>");
        sb.AppendLine($"<div class='info-row'><span class='info-label'>Hostname:</span><span class='info-value'>{hostname}</span></div>");
        sb.AppendLine($"<div class='info-row'><span class='info-label'>Tool Version:</span><span class='info-value'>1.0.0</span></div>");
        sb.AppendLine("</div>");

        sb.AppendLine("<div class='footer'>");
        sb.AppendLine("<p>Bhavani Technology - Bhavani Support Suite Pro v1.0.0</p>");
        sb.AppendLine("<p>Prepared by Lead Engineer: Dharmesh Varia | 2026</p>");
        sb.AppendLine("</div></body></html>");

        return await Task.FromResult(sb.ToString());
    }

    public static async Task<string> GenerateServiceReceiptAsync(string clientName, List<(string Item, string Status, string Notes)> serviceItems)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<!DOCTYPE html><html><head><title>Service Receipt</title>");
        sb.AppendLine("<style>");
        sb.AppendLine("body { font-family: 'Segoe UI', sans-serif; background: #fff; color: #333; margin: 40px; }");
        sb.AppendLine(".header { text-align: center; border-bottom: 3px solid #00ADB5; padding-bottom: 20px; }");
        sb.AppendLine(".header h1 { color: #00ADB5; }");
        sb.AppendLine("table { width: 100%; border-collapse: collapse; margin: 20px 0; }");
        sb.AppendLine("th { background: #00ADB5; color: white; padding: 10px; text-align: left; }");
        sb.AppendLine("td { padding: 10px; border-bottom: 1px solid #ddd; }");
        sb.AppendLine(".footer { text-align: center; margin-top: 30px; color: #888; font-size: 12px; }");
        sb.AppendLine("</style></head><body>");

        sb.AppendLine("<div class='header'>");
        sb.AppendLine("<h1>Service Receipt</h1>");
        sb.AppendLine($"<p>Bhavani Technology | {DateTime.Now:yyyy-MM-dd HH:mm:ss}</p>");
        sb.AppendLine($"<p>Client: {clientName}</p>");
        sb.AppendLine("</div>");

        sb.AppendLine("<table><thead><tr><th>Service Item</th><th>Status</th><th>Notes</th></tr></thead><tbody>");
        foreach (var item in serviceItems)
        {
            sb.AppendLine($"<tr><td>{item.Item}</td><td>{item.Status}</td><td>{item.Notes}</td></tr>");
        }
        sb.AppendLine("</tbody></table>");

        sb.AppendLine("<div class='footer'>");
        sb.AppendLine("<p>Bhavani Technology - Bhavani Support Suite Pro</p>");
        sb.AppendLine("<p>Prepared by Lead Engineer: Dharmesh Varia</p>");
        sb.AppendLine("</div></body></html>");

        return await Task.FromResult(sb.ToString());
    }

    public static async Task SaveReportAsync(string html, string filePath)
    {
        await File.WriteAllTextAsync(filePath, html);
    }

    public static void OpenReport(string filePath)
    {
        try
        {
            Process.Start(new ProcessStartInfo
            {
                FileName = filePath,
                UseShellExecute = true
            });
        }
        catch { }
    }
}
